drivers = {
          "VER": 1,
          "HAM": 2,
          "PER": 3,
          "LEC": 4,
          "NOR": 5,
          "RIC": 6,
          "SAI": 7,
          "ALO": 8,
          "RUS": 9,
          "ZHO": 10,
          "MAG": 11,
          "GAS": 12,
          "LAT": 13,
          "TSU": 14,
          "DEV": 15,
          "ALB": 16,
          "SCH": 17,
          "HUL": 18,
          "VAN": 19,
          "STR": 20,
          "HAR": 21,
          "OCO": 22,
          "SIR": 23,
          "VET": 24,
          "RAI" :25,
          "GRO": 26,
          "KUB": 27,
          "ERI": 28,
          "KVY": 29,
          "GIO": 30,
          "PIA": 31,
          "ANT": 32,
          "BEA": 33,
          "BOR": 34,
          "HAD": 35,
          "DOO": 36,
          "LAW": 37,
          "FIT": 38,
          "AIT": 39,
          "MSC": 40,
          "MAZ": 41,
          "SAR": 42,
          "COL": 43,
          "BOT": 44}

teams = {
         "Red Bull": 1,
         "Mercedes": 2,
         "Ferrari": 3,
         "McLaren": 4,
         "Red Bull Racing": 5,
         "Haas": 6,
         "Williams": 7,
         "Alpine": 8,
         'Kick Sauber': 9,
         "Alfa Romeo": 10,
         "Aston Martin": 11,
         "Toro Rosso": 12,
         "Renault": 13,
         "Sauber": 14,
         'Haas F1 Team': 15,
         'Alfa Romeo Racing': 16,
         'AlphaTauri': 17,
         "Force India": 18,
         'Racing Point': 19,
         }

compounds = {
    'SOFT' : 1,
    'MEDIUM' : 2,
    'HARD' : 3,
    'INTERMEDIATE' : 4,
    'WET' : 5,
    'UNKNOWN': 5,
    'SUPERHARD' : 3,
    'SUPERSOFT' : 1,
    'SOFT HARD' : 2,
    'SOFT SOFT' : 1,
    'ULTRASOFT' : 1,
    'HYPERSOFT' : 1,
}