drivers = {"HAM": 0,
          "VER": 1,
          "BOT": 2,
          "PER": 3,
          "LEC": 4,
          "NOR": 5,
          "RIC": 6,
          "SAI": 7,
          "ALO": 8,
          "RUS": 9,
          "ZHO": 10,
          "MAG": 11,
          "GAS": 12,
          "LAT": 13,
          "TSU": 14,
          "DEV": 15,
          "ALB": 16,
          "SCH": 17,
          "HUL": 18,
          "VAN" : 19,
          "STR": 20,
          "HAR": 21,
          "OCO": 22,
          "SIR": 23,
          "VET": 24,
          "RAI" : 25,
          "GRO": 26,
          "KUB": 27,
          "ERI": 28,
          "KVY": 29,
          "GIO": 30,
          "PIA": 31,
          "ANT": 32,
          "BEA": 33,
          "BOR": 34,
          "HAD": 35,
          "DOO": 36,
          "LAW": 37}

teams = {"Mercedes": 0,
         "Red Bull": 1,
         "Ferrari": 2,
         "Alpine": 3,
         "McLaren": 4,
         "Alfa Romeo": 5,
         "Aston Martin": 6,
         "Haas": 7,
         "Williams": 8,
         "Toro Rosso": 9,
         "Renault": 10,
         "Sauber": 11,
         "Red Bull Racing": 12,
         "Force India": 13,
         'Racing Point': 14,
         'Haas F1 Team': 15,
         'Alfa Romeo Racing': 16,
         'AlphaTauri': 17,
         'Kick Sauber': 18}

compounds = {
    'SOFT' : 0,
    'MEDIUM' : 1,
    'HARD' : 2,
    'INTERMEDIATE' : 3,
    'WET' : 4,
    'SUPERHARD' : 5,
    'SUPERSOFT' : 6,
    'SOFT HARD' : 7,
    'SOFT SOFT' : 8,
    'ULTRASOFT' : 9,
    'HYPERSOFT' : 10,
}